---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template will create WAFv2 Ipset, WebAcl with Cloudfront Scope, Web ACLs rules, Cloudwatch metric
              Sample Request Dashbaord with last 3 hour data.

Parameters:
  env:
    Description: The environment name being worked on
    Type: String
    AllowedValues:
      - prod
      - non-prod
  CloudFrontInfo:
    Description: Cloudfront Name.
    Type: String
  IPSetname:
    Description: The short name to identify ipsets.
    Type: String
  IPSetDescription:
    Description: Short description to identify ipsets.
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Environment
        Parameters:
          - env
      - 
        Label:
          default: IP Set Details
        Parameters:
          - IPSetname
          - IPSetDescription

Resources:
  SampleIPSet:
      Type: 'AWS::WAFv2::IPSet'
      Properties:
        Description: !Sub "${IPSetDescription}"
        Name: !Sub "${IPSetname}"
        Scope: CLOUDFRONT
        IPAddressVersion: IPV4
        Addresses:  
          - 111.11.11.11/32 # Random-Pub-IP-1
          - 122.12.12.1/32   #  Random-Pub-IP-2
          - 133.225.192.0/18  #  Random-Pub-IP-3

  CDNAccessIPRestrictionWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "myproject-${env}-cdn-${CloudFrontInfo}-WebACL"
      Scope: CLOUDFRONT
      DefaultAction:
        Block: {
      "CustomResponse": {
        "ResponseCode": 401,
        "CustomResponseBodyKey": "Unauthorized"
      }
    }
      Description: !Sub "To limit access of Cloudfront ${CloudFrontInfo}  from known IP ranges only"
      Rules:
        - Name: !Sub "myproject-${env}-cdn-${CloudFrontInfo}-WebACL-Rule1"
          Priority: 0
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt SampleIPSet.Arn
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "myproject-${env}-cdn-${CloudFrontInfo}-IpLimitationRule"
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "myproject-${env}-cdn-${CloudFrontInfo}-WebACLMetric"
      Capacity: 1

      CustomResponseBodies:
        Unauthorized:
          ContentType: TEXT_PLAIN
          Content: Unauthorized !
