---
- name: Git clone source repository..
  command: >
    git clone https://{{ git_username }}:{{ token }}@github.com/Jackuna/aws-swa.git -b lambda_deployer
- name: Git clone source repository..
  command: > 
    ls -ltr
- name: Git add new files to repo..
  command: >
    cp -r src aws-swa/lambda_folder

- name: Git add recent changes..
  command: >
    git add --all lambda_folder/src
  args:
    chdir: aws-swa
- name: Git Config username..
  command: >
    git config user.name {{ git_username }}
  args:
    chdir: aws-swa

- name: Git Config email..
  command: >
    git config user.email {{ git_username }}@cyberkeeda.com 
  args:
    chdir: aws-swa  
- name: Git commit recent changes..
  command: >
    git commit -m "Updated Latest code"
  args:
    chdir: aws-swa

- name: Git push recent changes..
  command:
    argv:
      - git 
      - push 
      - https://{{ git_username }}:{{ token }}@github.com/Jackuna/aws-swa.git 
      - -u 
      - lambda_deployer
  args:
    chdir: aws-swa
